import { AppDefinition } from '@/types'

export const apps: AppDefinition[] = [
  {
    id: 'my-computer',
    label: 'My Computer',
    icon: 'my-computer',
    component: () => import('./MyComputer/App'),
    defaultSize: { width: 640, height: 480 },
    defaultPosition: { x: 120, y: 80 },
    resizable: true,
  },
  {
    id: 'notepad',
    label: 'About Me',
    icon: 'notepad',
    component: () => import('./Notepad/App'),
    defaultSize: { width: 520, height: 380 },
    defaultPosition: { x: 160, y: 100 },
    resizable: true,
  },
  {
    id: 'outlook',
    label: 'Contact',
    icon: 'outlook',
    component: () => import('./Outlook/App'),
    defaultSize: { width: 560, height: 420 },
    defaultPosition: { x: 200, y: 120 },
    resizable: true,
  },
  {
    id: 'internet-explorer',
    label: 'Links',
    icon: 'ie',
    component: () => import('./InternetExplorer/App'),
    defaultSize: { width: 640, height: 480 },
    defaultPosition: { x: 140, y: 90 },
    resizable: true,
  },
  {
    id: 'terminal',
    label: 'Terminal',
    icon: 'terminal',
    component: () => import('./Terminal/App'),
    defaultSize: { width: 500, height: 340 },
    defaultPosition: { x: 180, y: 110 },
    resizable: true,
  },
  {
    id: 'paint',
    label: 'Skills',
    icon: 'paint',
    component: () => import('./Paint/App'),
    defaultSize: { width: 600, height: 460 },
    defaultPosition: { x: 130, y: 85 },
    resizable: true,
  },
  {
    id: 'winamp',
    label: 'WinAMP',
    icon: 'winamp',
    component: () => import('./WinAMP/App'),
    defaultSize: { width: 280, height: 420 },
    defaultPosition: { x: 80, y: 60 },
    resizable: false,
  },
  {
    id: 'minesweeper',
    label: 'Minesweeper',
    icon: 'minesweeper',
    component: () => import('./Minesweeper/App'),
    defaultSize: { width: 360, height: 400 },
    defaultPosition: { x: 220, y: 130 },
    resizable: false,
  },
  {
    id: 'snake',
    label: 'Snake',
    icon: 'snake',
    component: () => import('./Snake/App'),
    defaultSize: { width: 340, height: 380 },
    defaultPosition: { x: 240, y: 140 },
    resizable: false,
  },
  {
    id: 'solitaire',
    label: 'Solitaire',
    icon: 'solitaire',
    component: () => import('./Solitaire/App'),
    defaultSize: { width: 640, height: 480 },
    defaultPosition: { x: 150, y: 95 },
    resizable: false,
  },
  {
    id: 'recycle-bin',
    label: 'Recycle Bin',
    icon: 'recycle-bin',
    component: () => import('./RecycleBin/App'),
    defaultSize: { width: 480, height: 360 },
    defaultPosition: { x: 170, y: 105 },
    resizable: true,
  },
  {
    id: 'msdos',
    label: 'MS-DOS',
    icon: 'msdos',
    component: () => import('./MSDOS/App'),
    defaultSize: { width: 500, height: 340 },
    defaultPosition: { x: 190, y: 115 },
    resizable: true,
  },
  {
    id: 'network-places',
    label: 'Tech Stack',
    icon: 'network',
    component: () => import('./NetworkPlaces/App'),
    defaultSize: { width: 560, height: 420 },
    defaultPosition: { x: 160, y: 100 },
    resizable: true,
  },
  {
    id: 'readme',
    label: 'README.txt',
    icon: 'readme',
    component: () => import('./Readme/App'),
    defaultSize: { width: 460, height: 340 },
    defaultPosition: { x: 220, y: 80 },
    resizable: true,
  },
  {
    id: 'antivirus',
    label: 'Dr. Marburg Antivirus',
    icon: 'antivirus',
    component: () => import('./Antivirus/App'),
    defaultSize: { width: 420, height: 320 },
    defaultPosition: { x: 260, y: 110 },
    resizable: false,
  },
  {
    id: 'stress',
    label: 'stress.exe',
    icon: 'stress',
    component: () => import('./Stress/App'),
    defaultSize: { width: 360, height: 260 },
    defaultPosition: { x: 200, y: 140 },
    resizable: false,
  },
  {
    id: 'donotopen',
    label: 'DO NOT OPEN',
    icon: 'donotopen',
    component: () => import('./DoNotOpen/App'),
    defaultSize: { width: 320, height: 200 },
    defaultPosition: { x: 320, y: 180 },
    resizable: false,
  },
  {
    id: 'datamosh',
    label: 'Datamosh',
    icon: 'datamosh',
    component: () => import('./Datamosh/App'),
    defaultSize: { width: 360, height: 240 },
    defaultPosition: { x: 280, y: 120 },
    resizable: false,
  },
  {
    id: 'rabbit',
    label: 'FollowTheWhiteRabbit',
    icon: 'rabbit',
    component: () => import('./Rabbit/App'),
    defaultSize: { width: 420, height: 320 },
    defaultPosition: { x: 200, y: 100 },
    resizable: false,
  },
]
