import { AppDefinition } from '@/types'

export const apps: AppDefinition[] = [
  {
    id: 'my-computer',
    label: 'My Computer',
    icon: '/icons/my-computer.png',
    component: () => import('./MyComputer/App'),
    defaultSize: { width: 640, height: 480 },
    defaultPosition: { x: 120, y: 80 },
    resizable: true,
  },
  {
    id: 'notepad',
    label: 'About Me',
    icon: '/icons/notepad.png',
    component: () => import('./Notepad/App'),
    defaultSize: { width: 520, height: 380 },
    defaultPosition: { x: 160, y: 100 },
    resizable: true,
  },
  {
    id: 'outlook',
    label: 'Contact',
    icon: '/icons/outlook.png',
    component: () => import('./Outlook/App'),
    defaultSize: { width: 560, height: 420 },
    defaultPosition: { x: 200, y: 120 },
    resizable: true,
  },
  {
    id: 'internet-explorer',
    label: 'Links',
    icon: '/icons/ie.png',
    component: () => import('./InternetExplorer/App'),
    defaultSize: { width: 640, height: 480 },
    defaultPosition: { x: 140, y: 90 },
    resizable: true,
  },
  {
    id: 'terminal',
    label: 'Terminal',
    icon: '/icons/terminal.png',
    component: () => import('./Terminal/App'),
    defaultSize: { width: 500, height: 340 },
    defaultPosition: { x: 180, y: 110 },
    resizable: true,
  },
  {
    id: 'paint',
    label: 'Skills',
    icon: '/icons/paint.png',
    component: () => import('./Paint/App'),
    defaultSize: { width: 600, height: 460 },
    defaultPosition: { x: 130, y: 85 },
    resizable: true,
  },
  {
    id: 'winamp',
    label: 'WinAMP',
    icon: '/icons/winamp.png',
    component: () => import('./WinAMP/App'),
    defaultSize: { width: 280, height: 420 },
    defaultPosition: { x: 80, y: 60 },
    resizable: false,
  },
  {
    id: 'minesweeper',
    label: 'Minesweeper',
    icon: '/icons/minesweeper.png',
    component: () => import('./Minesweeper/App'),
    defaultSize: { width: 360, height: 400 },
    defaultPosition: { x: 220, y: 130 },
    resizable: false,
  },
  {
    id: 'snake',
    label: 'Snake',
    icon: '/icons/snake.png',
    component: () => import('./Snake/App'),
    defaultSize: { width: 340, height: 380 },
    defaultPosition: { x: 240, y: 140 },
    resizable: false,
  },
  {
    id: 'solitaire',
    label: 'Solitaire',
    icon: '/icons/solitaire.png',
    component: () => import('./Solitaire/App'),
    defaultSize: { width: 640, height: 480 },
    defaultPosition: { x: 150, y: 95 },
    resizable: false,
  },
  {
    id: 'recycle-bin',
    label: 'Recycle Bin',
    icon: '/icons/recycle-bin.png',
    component: () => import('./RecycleBin/App'),
    defaultSize: { width: 480, height: 360 },
    defaultPosition: { x: 170, y: 105 },
    resizable: true,
  },
  {
    id: 'msdos',
    label: 'MS-DOS',
    icon: '/icons/msdos.png',
    component: () => import('./MSDOS/App'),
    defaultSize: { width: 500, height: 340 },
    defaultPosition: { x: 190, y: 115 },
    resizable: true,
  },
  {
    id: 'network-places',
    label: 'Tech Stack',
    icon: '/icons/network.png',
    component: () => import('./NetworkPlaces/App'),
    defaultSize: { width: 560, height: 420 },
    defaultPosition: { x: 160, y: 100 },
    resizable: true,
  },
]
