import { ReactNode } from 'react'

// Shared 16-color-ish W95 palette. Each icon grid row is 16 chars,
// '.' = transparent, anything else looks up a fill here.
const P: Record<string, string> = {
  k: '#000000',
  w: '#ffffff',
  g: '#808080',
  s: '#c0c0c0',
  d: '#dfdfdf',
  b: '#000080',
  B: '#2a6fd6',
  c: '#008080',
  C: '#00ffff',
  y: '#ffff00',
  F: '#ffd24a',
  o: '#ff8800',
  r: '#ff0000',
  G: '#008000',
  L: '#00ff00',
  m: '#ff00ff',
  t: '#c08850',
}

type Grid = string[]

const ICONS: Record<string, Grid> = {
  'my-computer': [
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kssssssssssssk.',
    '.ksbbbbbbbbbbsk.',
    '.ksbCCbbbbbbbsk.',
    '.ksbbbbbbbbbbsk.',
    '.ksbbbbbbbbbbsk.',
    '.ksbbbbbbbbbbsk.',
    '.kssssssssssssk.',
    '.kkkkkkkkkkkkkk.',
    '......kssk......',
    '....kssssssk....',
    '..kkkkkkkkkkkk..',
    '..kssssssggssk..',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  notepad: [
    '...kkkkkkkkkk...',
    '...kwwwwwwwwk...',
    '...kwrwwwwwwk...',
    '...kwrwggggwk...',
    '...kwrwwwwwwk...',
    '...kwrwggggwk...',
    '...kwrwwwwwwk...',
    '...kwrwggggwk...',
    '...kwrwwwwwwk...',
    '...kwrwggggwk...',
    '...kwrwwwwwwk...',
    '...kwrwggggwk...',
    '...kwwwwwwwwk...',
    '...kkkkkkkkkk...',
    '................',
    '................',
  ],
  resume: [
    '..kkkkkkkkkk....',
    '..kwwwwwwwwkk...',
    '..kwwwwwwwwkkk..',
    '..kwbbbbbbwwkk..',
    '..kwbbbbbbwwwk..',
    '..kwwwwwwwwwwk..',
    '..kwggggggwwwk..',
    '..kwwwwwwwwwwk..',
    '..kwggggggwwwk..',
    '..kwwwwwwwwwwk..',
    '..kwggggggwwwk..',
    '..kwwwwwwwwwwk..',
    '..kwwGGwwwwwwk..',
    '..kwwwwwwwwwwk..',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  outlook: [
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kwwwwwwwwwwwwk.',
    '.kwkwwwwwwwwkwk.',
    '.kwwkwwwwwwkwwk.',
    '.kwwwkwwwwkwwwk.',
    '.kwwwwkwwkwwwwk.',
    '.kwwwwwkkwwwwwk.',
    '.kwwwwwwwwwwwwk.',
    '.kwwwwwwwwwwwwk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
    '................',
  ],
  ie: [
    '................',
    '.....BBBBBB.....',
    '...BBBBBBBBBB...',
    '..BBBB....BBBB..',
    '.BBBB.......BBB.',
    '.BBB........BBB.',
    '.BBBBBBBBBBBBBB.',
    '.BBBBBBBBBBBBBB.',
    '.BBB............',
    '.BBB............',
    '..BBBB......BB..',
    '...BBBBBBBBBB...',
    '.....BBBBBB.....',
    '................',
    '................',
    '................',
  ],
  terminal: [
    '.kkkkkkkkkkkkkk.',
    '.kbbbbbbbbbbbbk.',
    '.kkkkkkkkkkkkkk.',
    '.kkkkkkkkkkkkkk.',
    '.kkwkkkkkkkkkkk.',
    '.kkkwkkkkkkkkkk.',
    '.kkkkwkkkkkkkkk.',
    '.kkkwkkkkkkkkkk.',
    '.kkwkkkkkkkkkkk.',
    '.kkkkkkwwwwkkkk.',
    '.kkkkkkkkkkkkkk.',
    '.kkkkkkkkkkkkkk.',
    '.kkkkkkkkkkkkkk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  paint: [
    '.............tt.',
    '............tt..',
    '...........tt...',
    '..........tt....',
    '.........tt.....',
    '........ss......',
    '.......sk.......',
    '......kk........',
    '.kkkkkkkkkkkkkk.',
    '.kssssssssssssk.',
    '.ksrrkyykGGkBBk.',
    '.ksrrkyykGGkBBk.',
    '.ksmmkCCkggkwwk.',
    '.ksmmkCCkggkwwk.',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  winamp: [
    '.kkkkkkkkkkkkkk.',
    '.kssssssssssssk.',
    '.kssssssooosssk.',
    '.ksssssooossssk.',
    '.kssssooosssssk.',
    '.ksssoooooosssk.',
    '.kssssoooossssk.',
    '.ksssooossssssk.',
    '.kssooosssssssk.',
    '.ksooossssssssk.',
    '.ksoosssssssssk.',
    '.kssssssssssssk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ],
  minesweeper: [
    '................',
    '.......kk.......',
    '...k...kk...k...',
    '....k.kkkk.k....',
    '.....kkkkkk.....',
    '....kkwwkkkk....',
    '..kkkkwwkkkkkk..',
    '..kkkkkkkkkkkk..',
    '....kkkkkkkk....',
    '.....kkkkkk.....',
    '....k.kkkk.k....',
    '...k...kk...k...',
    '.......kk.......',
    '................',
    '................',
    '................',
  ],
  snake: [
    '................',
    '..LLLLLLLLLLLL..',
    '..LkLLLLLLLLLL..',
    '............LL..',
    '..LLLLLLLLLLLL..',
    '..LLLLLLLLLLLL..',
    '..LL............',
    '..LLLLLLLLLLLL..',
    '..LLLLLLLLLLLL..',
    '............LL..',
    '....LLLLLLLLLL..',
    '........LLLLLL..',
    '................',
    '................',
    '................',
    '................',
  ],
  solitaire: [
    '.....kkkkkkkkkk.',
    '.....kcccccccck.',
    '.....kcccccccck.',
    'kkkkkkkkkkkccck.',
    'kwwwwwwwwwkccck.',
    'kwwrrwrrwwkccck.',
    'kwrrrrrrrwkccck.',
    'kwrrrrrrrwkccck.',
    'kwwrrrrrwwkkkkk.',
    'kwwwrrrwwwk.....',
    'kwwwwrwwwwk.....',
    'kwwwwwwwwwk.....',
    'kwwwwwwwwwk.....',
    'kkkkkkkkkkk.....',
    '................',
    '................',
  ],
  'recycle-bin': [
    '................',
    '....kkkkkkkk....',
    '...kssssssssk...',
    '..kkkkkkkkkkkk..',
    '..kwwwwwwwwwwk..',
    '..kwwGGwwGGwwk..',
    '..kwwGwwwwGwwk..',
    '..kwwGGGGGGwwk..',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '....kwwwwwwk....',
    '....kwwwwwwk....',
    '.....kwwwwk.....',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  msdos: [
    '.kkkkkkkkkkkkkk.',
    '.kkkkkkkkkkkkkk.',
    '.kwwwwkkkkkkkkk.',
    '.kkkkkkkkkkkkkk.',
    '.kwwwwwwwkkkkkk.',
    '.kkkkkkkkkkkkkk.',
    '.kwwwkwwwkkkkkk.',
    '.kkkkkkkkkkkkkk.',
    '.kwwwwwkkkkkkkk.',
    '.kkkkkkkkkkkkkk.',
    '.kCCkkkkkkkkkkk.',
    '.kkkkkkkkkkkkkk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ],
  network: [
    'kkkkkkk.........',
    'kbbbbbk.........',
    'kbbbbbk.........',
    'kbbbbbk.........',
    'kkkkkkk.........',
    '..kkk...........',
    '.kkkkk..........',
    '.....g..........',
    '.....gggggg.....',
    '..........g.....',
    '.........kkkkkkk',
    '.........kbbbbbk',
    '.........kbbbbbk',
    '.........kbbbbbk',
    '.........kkkkkkk',
    '...........kkk..',
  ],
  'start-flag': [
    '................',
    '................',
    '....kkkkkkkkkk..',
    '...krrrrkGGGGk..',
    '...krrrrkGGGGk..',
    '..krrrrrkGGGGk..',
    '..kkkkkkkkkkkk..',
    '..kBBBBkyyyyyk..',
    '...kBBBkyyyyk...',
    '...kBBBkyyyyk...',
    '....kkkkkkkkkk..',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  volume: [
    '................',
    '................',
    '................',
    '.......kk.......',
    '......kkk..k....',
    '..kkkkkkk.k.k...',
    '..kkkkkkk.k.k...',
    '..kkkkkkk.k.k...',
    '..kkkkkkk.k.k...',
    '......kkk..k....',
    '.......kk.......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  brightness: [
    '................',
    '.......y........',
    '...y...y...y....',
    '................',
    '......yyyy......',
    '.....yyyyyy.....',
    '.y...yyyyyy...y.',
    '.....yyyyyy.....',
    '......yyyy......',
    '................',
    '...y...y...y....',
    '.......y........',
    '................',
    '................',
    '................',
    '................',
  ],
  folder: [
    '................',
    '................',
    '..kkkkk.........',
    '.kFFFFFk........',
    '.kFFFFFkkkkkkkk.',
    '.kFFFFFFFFFFFFk.',
    '.kFFFFFFFFFFFFk.',
    '.kFFFFFFFFFFFFk.',
    '.kFFFFFFFFFFFFk.',
    '.kFFFFFFFFFFFFk.',
    '.kFFFFFFFFFFFFk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
    '................',
  ],
  doc: [
    '...kkkkkkkkkk...',
    '...kwwwwwwwwk...',
    '...kwggggggwk...',
    '...kwwwwwwwwk...',
    '...kwggggggwk...',
    '...kwwwwwwwwk...',
    '...kwggggggwk...',
    '...kwwwwwwwwk...',
    '...kwggggggwk...',
    '...kwwwwwwwwk...',
    '...kwggggwwwk...',
    '...kwwwwwwwwk...',
    '...kkkkkkkkkk...',
    '................',
    '................',
    '................',
  ],
  warning: [
    '................',
    '.......kk.......',
    '......kyyk......',
    '......kyyk......',
    '.....kyyyyk.....',
    '.....kykkyk.....',
    '....kyykkyyk....',
    '....kyykkyyk....',
    '...kyyykkyyyk...',
    '...kyyyyyyyyk...',
    '..kyyyykkyyyyk..',
    '..kyyyyyyyyyyk..',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ],
  stress: [
    '................',
    '.kkkkkkkkkkkkkk.',
    '.krrrrrrrrrrrrk.',
    '.kkkkkkkkkkkkkk.',
    '.kssssssssssssk.',
    '.ksrrkssrrssssk.',
    '.kskkksskkssssk.',
    '.ksrrkssrkssssk.',
    '.ksrrkssrrkkssk.',
    '.kssssssssssssk.',
    '.kssrkssrkssssk.',
    '.kssrkssrkssssk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ],
  antivirus: [
    '...kkkkkkkkkkk..',
    '..ksssssssssssk.',
    '..ksGGsswwsLLsk.',
    '..ksGsssrssLssk.',
    '..ksssssrrsssrk.',
    '..ksssssrssssrk.',
    '..ksGsssrssLssk.',
    '..ksGGsssLLLssk.',
    '..ksssssrrrsssk.',
    '..kssssrrkrssrk.',
    '..ksssrrkkrrssk.',
    '..kkkkkkkkkkkkk.',
    '....k.kkkk.k....',
    '....kk.kk.kk....',
    '.....kk.kkk.....',
    '................',
  ],
  donotopen: [
    '................',
    '.....kkkkkk.....',
    '....krrrrrrk....',
    '...kryyyyyyrk...',
    '..krywwwwwwyrk..',
    '..krywkkkkwyrk..',
    '..krywkwwkwyrk..',
    '..krywkkkkwyrk..',
    '..krywkkkwwyrk..',
    '..krywwwwwwyrk..',
    '...kryyyyyyrk...',
    '....krrrrrrk....',
    '.....kkkkkk.....',
    '................',
    '................',
    '................',
  ],
  readme: [
    '...kkkkkkkkkk...',
    '...kwwwwwwwwk...',
    '...kwwbbbbwwk...',
    '...kwbbbbbbwk...',
    '...kwwwwwwwwk...',
    '...kwbbbbbbwk...',
    '...kwwwwwwwwk...',
    '...kwbbbbwwwk...',
    '...kwwwwwwwwk...',
    '...kwbbbbbbwk...',
    '...kwwwwwwwwk...',
    '...kwbbbbbwwk...',
    '...kwwwwwwwwk...',
    '...kkkkkkkkkk...',
    '................',
    '................',
  ],
  datamosh: [
    'kkkkkkkkkkkkkkkk',
    'kmCmCmCmCmCmCmCk',
    'kCkkmCkkmCkkmCkk',
    'kmCkkkmCkkmCkkmC',
    'kCmCmkmCmkmCmkmk',
    'kkkmCkkmkkkmCkkk',
    'kmCkkkmCkkmCkkkk',
    'kCmCmkmkkmCmCkmk',
    'kkkmkkmCmCkkmCkk',
    'kmCkmCkkmkkmCkmk',
    'kCkkmCmCmCkkmkkk',
    'kmCmCkkkmCmCmkmk',
    'kCkkkmCmCkkkmCkk',
    'kmCmCkkmkkmCkkkk',
    'kCmCmCmCmCmCmCkk',
    'kkkkkkkkkkkkkkkk',
  ],
  rabbit: [
    '....k....k......',
    '....kk..kk......',
    '....kwk.kwk.....',
    '....kwkkkwk.....',
    '....kwwwwwk.....',
    '...kwwwwwwwk....',
    '..kwwkkwkkwwk...',
    '..kwwkkwkkwwk...',
    '..kwwwwwwwwwk...',
    '..kwwwwrrwwwk...',
    '..kwwwwwwwwwk...',
    '...kwwwwwwwk....',
    '...kwwwwwwwk....',
    '....kwwwwwk.....',
    '.....kkkkk......',
    '................',
  ],
  bsod: [
    'bbbbbbbbbbbbbbbb',
    'bwwwwwwwwwwwwwwb',
    'bwbbbbbbbbbbbbwb',
    'bwbwwwwwwwwwwbwb',
    'bwbwbbbbbbbbwbwb',
    'bwbwbwwwwwwbwbwb',
    'bwbwbwbbbbwbwbwb',
    'bwbwbwbwwbwbwbwb',
    'bwbwbwbbbbwbwbwb',
    'bwbwbwwwwwwbwbwb',
    'bwbwbbbbbbbbwbwb',
    'bwbwwwwwwwwwwbwb',
    'bwbbbbbbbbbbbbwb',
    'bwwwwwwwwwwwwwwb',
    'bbbbbbbbbbbbbbbb',
    '................',
  ],
}

export type IconName = keyof typeof ICONS

interface PixelIconProps {
  name: string
  size?: number
  className?: string
}

export function PixelIcon({ name, size = 32, className }: PixelIconProps) {
  const grid = ICONS[name] ?? ICONS.doc
  const rects: ReactNode[] = []
  grid.forEach((row, y) => {
    let x = 0
    while (x < row.length) {
      const ch = row[x]
      if (ch === '.' || !P[ch]) {
        x++
        continue
      }
      let end = x + 1
      while (end < row.length && row[end] === ch) end++
      rects.push(
        <rect key={`${x}-${y}`} x={x} y={y} width={end - x} height={1} fill={P[ch]} />
      )
      x = end
    }
  })
  return (
    <svg
      viewBox="0 0 16 16"
      width={size}
      height={size}
      shapeRendering="crispEdges"
      className={className}
      aria-hidden
    >
      {rects}
    </svg>
  )
}

// Title bar button glyphs (minimize / maximize / restore / close)
export function TitleGlyph({ type }: { type: 'min' | 'max' | 'restore' | 'close' }) {
  if (type === 'min') {
    return (
      <svg viewBox="0 0 8 8" width={8} height={8} shapeRendering="crispEdges" aria-hidden>
        <rect x={0} y={6} width={6} height={2} fill="#000" />
      </svg>
    )
  }
  if (type === 'max') {
    return (
      <svg viewBox="0 0 8 8" width={8} height={8} shapeRendering="crispEdges" aria-hidden>
        <rect x={0} y={0} width={8} height={8} fill="#000" />
        <rect x={1} y={2} width={6} height={5} fill="#c0c0c0" />
      </svg>
    )
  }
  if (type === 'restore') {
    return (
      <svg viewBox="0 0 8 8" width={8} height={8} shapeRendering="crispEdges" aria-hidden>
        <rect x={2} y={0} width={6} height={5} fill="#000" />
        <rect x={3} y={1} width={4} height={3} fill="#c0c0c0" />
        <rect x={0} y={3} width={6} height={5} fill="#000" />
        <rect x={1} y={4} width={4} height={3} fill="#c0c0c0" />
      </svg>
    )
  }
  return (
    <svg viewBox="0 0 8 8" width={8} height={8} aria-hidden>
      <path d="M0.5 0.5 L7.5 7.5 M7.5 0.5 L0.5 7.5" stroke="#000" strokeWidth={1.6} />
    </svg>
  )
}
